///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexTestAutomationTrendyol
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("0c8352f3-a052-48da-ab6b-54aa9c56b00a", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RanorexTestAutomationTrendyolRepository repository.
        /// </summary>
        public static RanorexTestAutomationTrendyolRepository repo = RanorexTestAutomationTrendyolRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AccountNavigationWrapper.GirişYap' at 15;9.", repo.ApplicationUnderTest.AccountNavigationWrapper.GirişYapInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.AccountNavigationWrapper.GirişYap.Click("15;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginRegister.UEyeOl' at 25;12.", repo.ApplicationUnderTest.LoginRegister.UEyeOlInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.LoginRegister.UEyeOl.Click("25;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RegisterEmail' at 17;23.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.RegisterEmail.Click("17;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'zeynepakin10{RMenu down}' with focus on 'ApplicationUnderTest.RegisterEmail'.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.RegisterEmail.PressKeys("zeynepakin10{RMenu down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+Alt+Q' Press with focus on 'ApplicationUnderTest.RegisterEmail'.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(4));
            Keyboard.PrepareFocus(repo.ApplicationUnderTest.RegisterEmail);
            Keyboard.Press(System.Windows.Forms.Keys.Q | System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Alt, 16, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey up}{RMenu up}gmail.com' with focus on 'ApplicationUnderTest.RegisterEmail'.", repo.ApplicationUnderTest.RegisterEmailInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.RegisterEmail.PressKeys("{LControlKey up}{RMenu up}gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RegisterPasswordInput' at 23;25.", repo.ApplicationUnderTest.RegisterPasswordInputInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.RegisterPasswordInput.Click("23;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'abcdhefg' with focus on 'ApplicationUnderTest.RegisterPasswordInput'.", repo.ApplicationUnderTest.RegisterPasswordInputInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.RegisterPasswordInput.PressKeys("abcdhefg");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginRegister.Kadın' at 16;7.", repo.ApplicationUnderTest.LoginRegister.KadınInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.LoginRegister.Kadın.Click("16;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginRegister.TyBgBeigeTyBorderedTyCheckboxTyI1' at 6;15.", repo.ApplicationUnderTest.LoginRegister.TyBgBeigeTyBorderedTyCheckboxTyI1Info, new RecordItemIndex(9));
            repo.ApplicationUnderTest.LoginRegister.TyBgBeigeTyBorderedTyCheckboxTyI1.Click("6;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginRegister.TyBgBeigeTyBorderedTyCheckboxTyI2' at 6;16.", repo.ApplicationUnderTest.LoginRegister.TyBgBeigeTyBorderedTyCheckboxTyI2Info, new RecordItemIndex(10));
            repo.ApplicationUnderTest.LoginRegister.TyBgBeigeTyBorderedTyCheckboxTyI2.Click("6;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LoginRegister.UEyeOl1' at 30;10.", repo.ApplicationUnderTest.LoginRegister.UEyeOl1Info, new RecordItemIndex(11));
            repo.ApplicationUnderTest.LoginRegister.UEyeOl1.Click("30;10");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
